app:
  app-name: cmcc-onenet
  allow-generate-api: true
  allow-cross-domain-access: true

logging:
  config: classpath:log.xml

server:
  port: 8081
  session-timeout: 18000

spring:
  main:
    show_banner: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  data:
    jpa:
      repositories:
        enabled: true

cmcc:
  onenet:
    deviceId: 39333785
    api-key: 9UEjFtzBsVdbfr6DaV9VvLM3kos=
    
    